version: 0.2

phases:
  pre_build:
    commands:
      - npm i
      - npm run test || exit 0
  build:
    commands:
      - npm run build
      - npm ci --omit=dev

reports:
  jest-result:
    files:
      - junit.xml

artifacts:
  exclude-paths:
    - dist/**/*.test.js
  files:
    - node_modules/**/*
    - dist/**/*
  name: codebuild-demo/outputs/$(date +%Y-%m-%d)
